rpc:
  url: "http://127.0.0.1:9944"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  chain_id: "MADARA_DEVNET"

run:
  concurrency: 5
  shooters:
    - name: "transfer"
      shoot: 10000
    - name: "mint"
      shoot: 10000
  read_benches:
    - name: "Get Events"
      num_requests: 100
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

deployer:
  salt: "0x42"
  address: "0x06b09c5cca7e5ef944dc3be7514cc1ae5a6e267f0f1f2b5520e90dc00aecf6e1"
  signing_key: "0x076f2ccdb23f29bc7b69278e947c01c6160a31cf02c19d06d0f6e5ab1d768b86"
  legacy_account: false
